# Generated by Django 5.0.2 on 2024-04-14 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_admincomment_usercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_response', to='quiz.usercomment')),
            ],
        ),
    ]
