# Generated by Django 5.0.2 on 2024-04-14 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_comment_author_remove_comment_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='UserResponse2',
        ),
        migrations.CreateModel(
            name='AdminComment2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.result')),
            ],
        ),
        migrations.AlterField(
            model_name='userresponse2',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.admincomment2'),
        ),
        migrations.DeleteModel(
            name='AdminComment',
        ),
    ]
